name: First Workflow
on : [push]

jobs:
    run-shell-commands: 
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Maaz you are doing grate"
            - name: 
              run: | 
                node -v
                npm -v
                uname
                ls -l

               


